### ISSUE TITLE
Custom Waking up page

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#15]
Hi,

it would be nice to be able to define your own waiting page :)

Thanks.

**Comment by everythingguy** [comment]
Just set a file volume to the file /usr/src/app/views/placeholder.ejs and start with the original file [placeholder.ejs](https://github.com/ItsEcholot/ContainerNursery/blob/main/views/placeholder.ejs)

**Comment by ItsEcholot** [comment]
@JamesDAdams I think the easiest way to accomplish this is how @everythingguy described it. Or did you have something different in mind?

**Comment by JamesDAdams** [comment]
Yes it's work, thanks. It's better now 😁

![image](https://user-images.githubusercontent.com/20860324/134549491-94c20fdf-6477-43b3-ada1-9017c1c156f6.png)
