### ISSUE TITLE
Redirect wakup page

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#24]
Hi,

Currently when we go to the url of a service and it is off we are directed to the waiting page for the time that the container raises the problem and that we are not direct if the url is not is not the same, exemple :  

https://komga.domaine.com <-- We are redirect to wake up page

https://komga.domaine.com/book/02MZB8FBMYSXS <-- **We are not** redirected to wake up page

**Comment by ItsEcholot** [comment]
This could very well be a bug, thanks for the report, I will take a look at this soon.
