### ISSUE TITLE
Container Nursery docker image not working on ARM

### ISSUE THREAD

**Issue by kn-f** [ItsEcholot/ContainerNursery#36]
Existing docker image is not working on ARM machines probably due to the fact that the image is built just for x86 machines.

As a temporary workaround I'm using this _Dockerfile_:
    
    FROM node:alpine

    RUN apk add --no-cache git

    WORKDIR /usr/src/app
    RUN git clone https://github.com/ItsEcholot/ContainerNursery.git .
    RUN npm install
    RUN npm run build

    CMD ["node", "build/index.js"]

And this as _docker-compose.yml_:

    services:
      containernursery:
        build:
          context: .
        image: containernursery
        container_name: containernursery
        networks:
          - proxy
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/home/xxxx/xxxx/config:/usr/src/app/config'
        labels:
          com.centurylinklabs.watchtower.enable: false

        restart: unless-stopped

    networks:
      proxy:
        external: true

Hope this helps ARM users as the application is extremely useful on low RAM devices.

EDIT: Corrected formatting & typos

**Comment by ItsEcholot** [comment]
Good idea, I will look into creating an image compatible with ARM.

**Comment by kn-f** [comment]
Works like a charm! (BTW I'm on an aarch64 architecture)
I'm not going to use this image at the moment due to the issue in #37.
Once that's solved I'll switch to this image.

**Comment by ItsEcholot** [comment]
Glad to hear it.
`arm64` and `aarch64` should be the same, no?

**Comment by kn-f** [comment]
Correct :)
