### ISSUE TITLE
FileBrowser container infinite loading

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#42]
Hi,

with filebrowser/filebrowser docker image i have infinite loging with this in the log : 
![image](https://user-images.githubusercontent.com/20860324/213860816-dfb4cb4c-e546-4294-b696-c87f6a4b57d4.png)

Thanks.

**Comment by ItsEcholot** [comment]
On a quick glance I would this is probably because of Docker Healthcheck. You could either try to disable the Docker Healthcheck or lower ContainerNurserys Log Level.
