### ISSUE TITLE
High CPU usage randomly

### ISSUE THREAD

**Issue by webysther** [ItsEcholot/ContainerNursery#48]
Sometimes the loop in frontend get stucked and use huge amount of cpu because the refresh rate is too intense, will be nice to have a ENV to change the refresh rate to a aproppriate value:

![image](https://github.com/ItsEcholot/ContainerNursery/assets/750007/2bf4033b-7f51-4be9-b487-baffda8e7405)

This block the reverse proxy to get the response from the service and the loop happens.

![image](https://github.com/ItsEcholot/ContainerNursery/assets/750007/e09bc6c0-86fd-4bac-b774-0f798b6763a6)

This only fixes when refresh manually the page.

**Comment by ItsEcholot** [comment]
Have you had the chance to find the culprit of this with enabled Debug logging?

**Comment by webysther** [comment]
> Have you had the chance to find the culprit of this with enabled Debug logging?

No, after a few occurrencies I removed from my stack. Maybe consider in future if add a option to change the refresh rate on frontend.
